//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksCopy
    {
        public int IDBooksCopy { get; set; }
        public int IDStudent { get; set; }
        public int IDBook { get; set; }
        public Nullable<int> IDBookState { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookState BookState { get; set; }
        public virtual Student Student { get; set; }
    }
}
