//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingLine = new HashSet<BookingLine>();
        }
    
        public int IDBooking { get; set; }
        public int IDStudent { get; set; }
        public Nullable<int> IDManager { get; set; }
        public int IDCooperative { get; set; }
        public System.DateTime BookingDate { get; set; }
        public bool TradeConfirmation { get; set; }
    
        public virtual Cooperative Cooperative { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingLine> BookingLine { get; set; }
    }
}
