//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksCopyTransferLine
    {
        public int IDBooksCopyTransferLine { get; set; }
        public int IDBooksCopyTransfer { get; set; }
        public int IDBooksCopy { get; set; }
        public int IDCooperativeFrom { get; set; }
        public int IDCooperativeTo { get; set; }
        public int State { get; set; }
    
        public virtual BooksCopy BooksCopy { get; set; }
        public virtual BooksCopyTransfer BooksCopyTransfer { get; set; }
        public virtual Cooperative Cooperative { get; set; }
        public virtual Cooperative Cooperative1 { get; set; }
    }
}
