//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingLine
    {
        public int IDBookingLine { get; set; }
        public int IDBooking { get; set; }
        public int IDBooksCopy { get; set; }
        public int BookingState { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual BooksCopy BooksCopy { get; set; }
    }
}
