//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livre()
        {
            this.LivresAuteurs = new HashSet<LivresAuteurs>();
        }
    
        public int IDLivre { get; set; }
        public string noISBN { get; set; }
        public string noEAN { get; set; }
        public string noUPC { get; set; }
        public string Titre { get; set; }
        public int nbPages { get; set; }
        public double prix { get; set; }
        public int IDEtatLivre { get; set; }
    
        public virtual EtatLivre EtatLivre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LivresAuteurs> LivresAuteurs { get; set; }
    }
}
