//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivresAuteurs
    {
        public int IDLivresAuteurs { get; set; }
        public int IDAuteur { get; set; }
        public int IDLivre { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
