//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryManagementEntities : DbContext
    {
        public LibraryManagementEntities()
            : base("name=LibraryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<BookingLine> BookingLine { get; set; }
        public virtual DbSet<BooksAuthors> BooksAuthors { get; set; }
        public virtual DbSet<BooksCopy> BooksCopy { get; set; }
        public virtual DbSet<BookState> BookState { get; set; }
        public virtual DbSet<Cooperative> Cooperative { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    }
}
