//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livre()
        {
            this.LivresAuteurs = new HashSet<LivresAuteurs>();
        }
    
        public int IDLivre { get; set; }
        public string noISBN { get; set; }
        public string noEAN { get; set; }
        public string noUPC { get; set; }
        public string Titre { get; set; }
        public int nbPages { get; set; }
        public double prix { get; set; }
        public int IDEtatLivre { get; set; }
    
        public virtual EtatLivre EtatLivre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LivresAuteurs> LivresAuteurs { get; set; }
    }
}
