//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public int IDResources { get; set; }
        public int IDLanguage { get; set; }
        public string TextName { get; set; }
        public string Description { get; set; }
    }
}
